INSERT INTO "Skill" (name, description) 
VALUES ('React', 'A JavaScript library for building user interfaces'),
        ('GraphQL', 'A query language for your API'),
        ('TypeScript', 'A typed superset of JavaScript that compiles to plain JavaScript'),
        ('Prisma', 'A modern database toolkit'),
        ('NestJS', 'A progressive Node.js framework for building efficient, reliable and scalable server-side applications'),
        ('Next.js', 'The React Framework for Production'),
        ('Tailwind CSS', 'A utility-first CSS framework for rapidly building custom designs'),
        ('Docker', 'A platform for building, sharing, and running applications with containers'),
        ('Kubernetes', 'An open-source system for automating deployment, scaling, and management of containerized applications'),
        ('AWS', 'A secure cloud services platform, offering compute power, database storage, content delivery and other functionality to help businesses scale and grow'),
        ('Azure', 'A cloud computing service created by Microsoft for building, testing, deploying, and managing applications and services'),
        ('Google Cloud', 'A suite of cloud computing services that runs on the same infrastructure that Google uses internally for its end-user products, such as Google Search, Gmail, file storage, and YouTube'),
        ('Firebase', 'A platform developed by Google for creating mobile and web applications'),
        ('Vercel', 'A cloud platform for static sites and Serverless Functions that fits perfectly with your workflow'),
        ('Jest', 'A delightful JavaScript Testing Framework with a focus on simplicity'),
        ('Cypress', 'Fast, easy and reliable testing for anything that runs in a browser'),
        ('Storybook', 'An open source tool for developing UI components in isolation for React, Vue, and Angular'),
        ('Figma', 'A vector graphics editor and prototyping tool which is primarily web-based, with additional offline features enabled by desktop applications for macOS and Windows'),
        ('PostgreSQL', 'A powerful, open source object-relational database system');